#!/bin/bash

set -eux -o pipefail

if [[ -z $(git status --porcelain -- "$PR_FILE_CHECK") ]]; then
    echo "No changes made."
    exit 0
fi

git switch -c "${GITHUB_JOB}-$(date +%s)"
git commit -i "$PR_FILE_CHECK" -m "$PR_TITLE"
git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
git push origin HEAD

PR_URL=$(gh pr create --title "$PR_TITLE" --body '' | tail -n 1) || exit $?
gh pr merge --auto --squash "$PR_URL" || echo "Branch protections are not enabled so auto-merging cannot be enabled."
