apiVersion: tekton.dev/v1
kind: Task
metadata:
  namespace: rhel-lightspeed-tenant
  name: get-version

spec:
  description: Extract project version from pyproject.toml
  params:
    - name: source_artifact
      description: The Trusted Artifact URI pointing to the artifact with the application source code.
      type: string

  results:
    - name: version
      description: Project version (also valid as a container tag)

  volumes:
    - name: workdir
      emptyDir: {}

  stepTemplate:
    volumeMounts:
      - name: workdir
        mountPath: /var/workdir

  steps:
    - name: use-trusted-artifact
      image: quay.io/konflux-ci/build-trusted-artifacts:latest@sha256:dc542700b2e7ba806adfab360682d491c069bc2d6157d235c26adbe09480e26b
      args:
        - use
        - $(params.source_artifact)=/var/workdir/source

    - name: extract-version
      image: registry.redhat.io/ubi10/s2i-base:latest
      workingDir: /var/workdir/source
      script: |
        #!/usr/bin/env python3
        import tomllib, pathlib
        version = tomllib.loads(pathlib.Path("pyproject.toml").read_text())["project"]["version"]
        pathlib.Path("$(results.version.path)").write_text(version)
        print(f"version={version}")
