name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Units

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.ref }}

      - name: Install Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: '3.11'

      - name: Install test deps
        run: python -m pip install pytest

      - name: Run tests
        run: pytest test

