name: Triage

on:
  issues:
    types:
      - opened
      - reopened

  pull_request_target:

jobs:
  triage:
    runs-on: ubuntu-latest
    name: Label

    steps:
      - name: Environment
        run: env

      - name: Debug
        run: echo ${{ github.event }}

      - name: Debug more
        run: echo ${{ github }}

      - name: Label pull requests
        uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/pr-labeler.yml
        if: github.event == 'pull_request_target'

      - name: Label issues
        uses: github/issue-labeler@v2.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          not-before: 2021-12-07T07:00:00Z
          configuration-path: .github/issue-labeler.yml
          enable-versioned-regex: 0
        if: github.event == 'issues'


