name: Update

on:
  schedule:
    - cron: "0 6 * * 4"  # Weekly Thursday at 06:00 UTC

  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  update_base_image:
    name: Base image
    runs-on: ubuntu-latest
    container:
      image: quay.io/rhel_lightspeed/ci

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Update base image
        run: update-image-refs -d

      - name: Open a PR if changes were made
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: "Update base image"
          PR_FILE_CHECK: Containerfile
        run: scripts/create-pr

  update_task_refs:
    name: Task refs
    runs-on: ubuntu-latest
    container:
      image: quay.io/rhel_lightspeed/ci

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Update task references
        run: update-task-refs -o -f .tekton/

      - name: Open a PR if changes were made
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: "Update task references"
          PR_FILE_CHECK: .tekton/
        run: scripts/create-pr
