name: Update refs

on:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  update_base_image:
    name: Update base image
    runs-on: ubuntu-latest
    container:
      image: quay.io/rhel_lightspeed/ci

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Debug
        run: |
          env | sort
          pwd
          git remote -v
          git status

      - name: Update base image
        run: update-image-refs -d

      # - name: Open a PR if changes were made
      #   env:
      #     GIT_AUTHOR_NAME: github-actions[bot]
      #     GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
      #     GIT_COMMITTER_NAME: github-actions[bot]
      #     GIT_COMMITTER_EMAIL: github-actions[bot]@users.noreply.github.com
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: scripts/create-pr.sh
